**Data Encapsulation and Data Abstraction:**


**1. Create a class Student with attributes name (private), age (protected), and marks (public). Implement methods to set and get the values of the private and protected attributes. Create an instance of the class and demonstrate how to use these methods to access and modify the attributes.**

**2. Create a base class Shape with a protected attribute area. Implement subclasses Circle and Rectangle that calculate their respective areas. Make use of protected members to store and access the calculated areas.**

**3. Write a class Calculator that implements a method evaluate expression() to calculate the result of an arithmetic expression following the PEMDAS rule.**

**4. Create a program that reads data from a CSV file named data.csv containing student names and their scores. Implement a class Student with attributes name and score. Read the data from the CSV file and create instances of the Student class for each student. Compute the average for the class using a numpy function**



In [1]:
class Student:
    def __init__(self, name, age, marks):
        self.__name = name  # private attribute
        self._age = age  # protected attribute
        self.marks = marks  # public attribute

    # Method to set the name
    def set_name(self, name):
        self.__name = name

    # Method to get the name
    def get_name(self):
        return self.__name

    # Method to set the age
    def set_age(self, age):
        self._age = age

    # Method to get the age
    def get_age(self):
        return self._age

# Create an instance of the Student class
s = Student("Siddhi", 20, 95)

# Access and modify the attributes using methods
print(s.get_name())  # Output: Siddhi
s.set_name("Lipare")
print(s.get_name())  # Output: Lipare

print(s.get_age())  # Output: 20
s.set_age(22)
print(s.get_age())  # Output: 22

print(s.marks)  # Output: 95


Siddhi
Lipare
20
22
95


In [5]:
import math

class Shape:
    def __init__(self):
        self._area = 0  # protected attribute

    def calculate_area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        super().__init__()
        self.radius = radius

    def calculate_area(self):
        self._area = math.pi * self.radius ** 2
        return self._area

class Rectangle(Shape):
    def __init__(self, length, width):
        super().__init__()
        self.length = length
        self.width = width

    def calculate_area(self):
        self._area = self.length * self.width
        return self._area

# Test the code
c = Circle(5)
r = Rectangle(4, 6)

print(c.calculate_area())  # Output: 78.53981633974483
print(r.calculate_area())  # Output: 24



78.53981633974483
24


In [4]:
# Calculator using PEMDAS Rule:

class Calculator:
    def evaluate_expression(self, expression):
        return eval(expression)

calc = Calculator()
result = calc.evaluate_expression("2 + 2 * 2")
print(result)  # Output: 6


6


In [2]:
from google.colab import files
files.upload()

Saving data.csv to data.csv


{'data.csv': b'name,score\nSiddhi, 95\nAryan, 85\nKishore, 75\nAkshat, 80\n'}

In [3]:
import csv
import numpy as np

class Student:
    def __init__(self, name, score):
        self.name = name
        self.score = score

students = []

# Read from CSV
with open('data.csv', 'r') as file:
    reader = csv.reader(file)
    next(reader)  # Skip the header row
    for row in reader:
        students.append(Student(row[0], int(row[1])))

# Compute the average score using numpy
scores = [student.score for student in students]
average_score = np.mean(scores)
print(f"The class average is: {average_score}")


The class average is: 83.75


**Welcome To Numpy**

This assignment will help you the explore the Numpy library and its various uses. It would also cover some use cases about how numpy makes Machine Learning and Data Science calculations easy and fast. This assignment is made in order to encourage you to explore more and more builtin functions of this library and their usage. For all problems, you need to print the output.




**Importing Numpy**

The first step involves importing Numpy so that you can start using it right away. There are a lot of ways to do so depending upon how you want to use library or some functions of it. In general, we import it all together and in order to avoid writing numpy again and again, we abbreviate it in some form. For ex. np. Import the Numpy library as np in the below cell.

In [6]:
import numpy as np

**Arrays In Numpy**

As already discussed in class, there are various ways of making numpy arrays. In the below cells we would test your ability to implement them correctly.

**Create a numpy array of 1's of user defined dimensions**

Take input for 2 dimensions : N and M, create a 2D matrix of 1's. Note : In general you can make numpy arrays of any number of dimensions. eg. 3, 4, and so on...

In [10]:
# Take user input for dimensions N and M
N = int(input("Enter the number of rows (N): "))
M = int(input("Enter the number of columns (M): "))

# Create a 2D numpy array of ones with dimensions N x M
array_of_ones = np.ones((N, M), dtype=int)

# Display the array
print("Generated 2D array of ones:")
print(array_of_ones)


Enter the number of rows (N): 3
Enter the number of columns (M): 4
Generated 2D array of ones:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**Create an empty array Using Numpy**

When you print your array, you might see random values in your array. Repeat instructions as mentioned for previous cell.


In [11]:
# Taking input for dimensions N and M
N = int(input("Enter the number of rows (N): "))
M = int(input("Enter the number of columns (M): "))

# Creating an empty numpy array with dimensions N x M
empty_array = np.empty((N, M))

print("Empty Numpy Array:")
print(empty_array)


Enter the number of rows (N): 3
Enter the number of columns (M): 4
Empty Numpy Array:
[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]


4
**Create a numpy array of 0's of user defined dimensions**

Repeat instructions as mentioned previously


In [13]:
# Taking input for dimensions N and M
N = int(input("Enter the number of rows (N): "))
M = int(input("Enter the number of columns (M): "))

# Creating an empty numpy array with dimensions N x M
zeros_array = np.zeros((N, M))

print("Empty Numpy Array:")
print(zeros_array)


Enter the number of rows (N): 3
Enter the number of columns (M): 4
Empty Numpy Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Create a numpy array from numbers 1 to 10 using inbuilt functions**

This task can be implemented using 2 functions : **arange()** and **linspace()**. You have to make use of both of them in cells given below

In [16]:
# Using 'arange()' function

array_arange = np.arange(1, 11)

print("Array created using arange():")
print(array_arange)


Array created using arange():
[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
# Using linspace() function:

array_linspace = np.linspace(1, 10, 10)

print("Array created using linspace():")
print(array_linspace)


Array created using linspace():
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


**Convert a simple list to array**

Create a 1D list and a 2D list and convert them to numpy arrays. You need to print the type of both after conversion in order to check if they are really converted or not.

In [20]:
# Creating a 1D list
list_1d = [1, 2, 3, 4, 5]

# Converting the 1D list to a numpy array
array_1d = np.array(list_1d)

print("Original 1D List:", list_1d)
print("Converted 1D Numpy Array:", array_1d)
print("Type of Converted 1D Numpy Array:", type(array_1d))


Original 1D List: [1, 2, 3, 4, 5]
Converted 1D Numpy Array: [1 2 3 4 5]
Type of Converted 1D Numpy Array: <class 'numpy.ndarray'>


In [21]:
# Creating a 2D list
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Converting the 2D list to a numpy array
array_2d = np.array(list_2d)

print("\nOriginal 2D List:")
for row in list_2d:
    print(row)

print("\nConverted 2D Numpy Array:")
print(array_2d)
print("Type of Converted 2D Numpy Array:", type(array_2d))



Original 2D List:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Converted 2D Numpy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type of Converted 2D Numpy Array: <class 'numpy.ndarray'>


**Conversion Of Data Types in Numpy arrays**

In this problem, you need to convert float numpy array to integer type and vice versa. You need to print the array after each conversion.

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

print("Original Array:")
print(a)

# Convert float array to integer
a_integer = a.astype(int)
print("\nArray after converting to integer:")
print(a_integer)

# Convert integer array back to float
a_float = a_integer.astype(float)
print("\nArray after converting back to float:")
print(a_float)


Original Array:
[[1. 2. 3.]
 [4. 5. 6.]]

Array after converting to integer:
[[1 2 3]
 [4 5 6]]

Array after converting back to float:
[[1. 2. 3.]
 [4. 5. 6.]]


**Given below is an array of 20 elements. Convert this array into 2D matrices of dimensions 1 x 20, 2 x 10, 4 x 5, 5 x 4, 10 x 2 and 20 x 1**

**For each given dimensions, you need to print the new array**

**For the 1 x 20 array, print every third element using indexing & slicing**

**Use the array splitter function for the 10 x 2 array having results with 3 elements**

**Concatenate arrays 10 x 2 and 20 x 1 using concatenate(), hstack(),vstack, dstack() or using axis values, you may combine reshape() for either arrays so that all the functions work, provide comments while you stack arrays for the reader to have clarity for the steps**

In [25]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Convert to 1x20 array
array_1x20 = a.reshape(1, -1)
print("1 x 20 Array:")
print(array_1x20)


1 x 20 Array:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]


In [26]:
# Convert to 2x10 array
array_2x10 = a.reshape(2, 10)
print("\n2 x 10 Array:")
print(array_2x10)



2 x 10 Array:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [27]:
# Convert to 4x5 array
array_4x5 = a.reshape(4, 5)
print("\n4 x 5 Array:")
print(array_4x5)



4 x 5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [28]:
# Convert to 5x4 array
array_5x4 = a.reshape(5, 4)
print("\n5 x 4 Array:")
print(array_5x4)



5 x 4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [29]:
# Convert to 10x2 array
array_10x2 = np.array_split(a, 10)
print("\n10 x 2 Array:")
for row in array_10x2:
    print(row)



10 x 2 Array:
[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]
[11 12]
[13 14]
[15 16]
[17 18]
[19 20]


In [32]:
# Convert to 20x1 array
array_20x1 = a.reshape(-1, 1)
print("\n10 x 2 Array:")
for row in array_20x1:
    print(row)


10 x 2 Array:
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]


In [30]:
# Print every third element of 1x20 array
every_third = array_1x20[:, ::3]
print("\nEvery Third Element of 1 x 20 Array:")
print(every_third)


Every Third Element of 1 x 20 Array:
[[ 1  4  7 10 13 16 19]]


In [39]:
# Concatenate 10x2 and 20x1 arrays

# using concatenate()
array_20x1 = a.reshape(-1, 1)
concatenated_array = np.concatenate((array_10x2[3], array_20x1), axis=None)
print("\nConcatenated Array:")
print(concatenated_array)



Concatenated Array:
[ 7  8  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [41]:
# Concatenate 10x2 and 20x1 arrays

# using hstack()
array_10x2 = a.reshape(10, 2)
array_20x1 = a.reshape(10, 2)
concatenated_array_hstack = np.hstack((array_10x2, array_20x1))
print("\nConcatenated Array using hstack():")
print(concatenated_array_hstack)


Concatenated Array using hstack():
[[ 1  2  1  2]
 [ 3  4  3  4]
 [ 5  6  5  6]
 [ 7  8  7  8]
 [ 9 10  9 10]
 [11 12 11 12]
 [13 14 13 14]
 [15 16 15 16]
 [17 18 17 18]
 [19 20 19 20]]


In [42]:
# Concatenate 10x2 and 20x1 arrays

# using hstack()

concatenated_array_vstack = np.vstack((array_10x2, array_20x1))
print("\nConcatenated Array using vstack():")
print(concatenated_array_vstack)


Concatenated Array using vstack():
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [43]:
# Concatenate 10x2 and 20x1 arrays

# using dstack()

concatenated_array_dstack = np.dstack((array_10x2, array_20x1))
print("\nConcatenated Array using dstack():")
print(concatenated_array_dstack)


Concatenated Array using dstack():
[[[ 1  1]
  [ 2  2]]

 [[ 3  3]
  [ 4  4]]

 [[ 5  5]
  [ 6  6]]

 [[ 7  7]
  [ 8  8]]

 [[ 9  9]
  [10 10]]

 [[11 11]
  [12 12]]

 [[13 13]
  [14 14]]

 [[15 15]
  [16 16]]

 [[17 17]
  [18 18]]

 [[19 19]
  [20 20]]]


**Find maximum element in array and print its value and its index using numpy inbuilt functions**

In [44]:
a = np.array([100,40,30,106,4589,2,34,76,9777,1023,56,62,395])

# Find maximum element and its index
max_value = np.max(a)
max_index = np.argmax(a)

print("Array:", a)
print("Maximum Value:", max_value)
print("Index of Maximum Value:", max_index)

Array: [ 100   40   30  106 4589    2   34   76 9777 1023   56   62  395]
Maximum Value: 9777
Index of Maximum Value: 8


**Print Dimensions Of The Given Array, shape of the array and size**

**Iterate through the array 'a' skipping a value and printing the next value.**

**Implement reshape on this array with your choice of parameters (not 1D)**

**Make a 1D array also and sort the array, then find the indices of values ==6 using numpy functions**

**On the 1D array, implement a numpy function to print values only above 100**



In [49]:
a = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8], [7, 8, 9], [10, 102, 546]])

# Print dimensions, shape, and size of the array
print("Array Dimensions:", a.ndim)
print("Array Shape:", a.shape)
print("Array Size:", a.size)

# Iterate through the array skipping a value and printing the next value
print("\nIterating Through the Array:")
for i in range(0, a.size, 2):
    print(a.flat[i])


Array Dimensions: 2
Array Shape: (5, 3)
Array Size: 15

Iterating Through the Array:
1
3
5
6
8
8
10
546


In [50]:
# Reshape the array with chosen parameters
reshaped_array = a.reshape(3, -1)
print("\nReshaped Array:")
print(reshaped_array)


Reshaped Array:
[[  1   2   3   4   5]
 [  6   6   7   8   7]
 [  8   9  10 102 546]]


In [51]:
# Create a 1D array and sort it
a_1d = a.flatten()
sorted_array = np.sort(a_1d)
print("\nSorted 1D Array:")
print(sorted_array)


Sorted 1D Array:
[  1   2   3   4   5   6   6   7   7   8   8   9  10 102 546]


In [52]:
# Find indices of values equal to 6
indices_equal_to_6 = np.where(sorted_array == 6)[0]
print("\nIndices of Values equal to 6:", indices_equal_to_6)



Indices of Values equal to 6: [5 6]


In [53]:
# Print values above 100 in the 1D array
values_above_100 = sorted_array[sorted_array > 100]
print("\nValues Above 100:", values_above_100)


Values Above 100: [102 546]


**Create a NumPy array with the integers from your birthdate (year, month, and day)**

**Retrieve the year.**

**Replace the year with the current year**

**Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?**

In [54]:
year = 2003
month = 8
day = 8

# Create a NumPy array with birthdate integers
birthdate_array = np.array([year, month, day])

print("Birthdate Array:", birthdate_array)

Birthdate Array: [2003    8    8]


In [56]:
# Retrieve the year from the birthdate array
retrieved_year = birthdate_array[0]

print("Retrieved Year:", retrieved_year)


Retrieved Year: 2023


In [57]:
import datetime

# Get the current year
current_year = datetime.datetime.now().year

# Replace the year in the birthdate array with the current year
birthdate_array[0] = current_year

print("Updated Birthdate Array:", birthdate_array)


Updated Birthdate Array: [2023    8    8]


In [60]:
# Create an array with every 3rd number from 567 to 890
every_third_array = np.arange(567, 891, 3)

print("Every Third Array:", every_third_array)

# Find the 8th and 15th numbers in the every third array
eighth_number = every_third_array[7]  # Index is 7 because indexing starts from 0
fifteenth_number = every_third_array[14]

print("\n8th Number:", eighth_number)
print("15th Number:", fifteenth_number)


Every Third Array: [567 570 573 576 579 582 585 588 591 594 597 600 603 606 609 612 615 618
 621 624 627 630 633 636 639 642 645 648 651 654 657 660 663 666 669 672
 675 678 681 684 687 690 693 696 699 702 705 708 711 714 717 720 723 726
 729 732 735 738 741 744 747 750 753 756 759 762 765 768 771 774 777 780
 783 786 789 792 795 798 801 804 807 810 813 816 819 822 825 828 831 834
 837 840 843 846 849 852 855 858 861 864 867 870 873 876 879 882 885 888]

8th Number: 588
15th Number: 609


**Evaluate (PEMDAS):**
1. ((((12+7)*2)-4)/2)-13
2. 5+5/5
3. 2*5//4
4. 2\*\*3\*\*2
5. (2\*\*3)\*\*2

In [61]:
result1 = ((((12 + 7) * 2) - 4) / 2) - 13
print("Result 1:", result1)

Result 1: 4.0


In [63]:
result2 = 5 + 5 / 5
print("Result 2:", result2)

Result 2: 6.0


In [64]:
result3 = 2 * 5 // 4
print("Result 3:", result3)

Result 3: 2


In [65]:
result4 = 2 ** 3 ** 2
print("Result 4:", result4)

Result 4: 512


In [66]:
result5 = (2 ** 3) ** 2
print("Result 5:", result5)

Result 5: 64
